# Data path. adjust them!
# common:
#   image_file: "/home/gisen/Downloads/calib_dataset/single_scene_calibration/0.png"
#   pcd_file: "/home/gisen/Downloads/calib_dataset/single_scene_calibration/0.pcd"
#   result_file: "/home/gisen/pcd/pantory/result/result3.txt"

common:
  image_file: "/home/gisen/pcd/pantory/pic/0.jpg"
  pcd_file: "/home/gisen/pcd/pantory/pid/0.pcd"
  result_file: "/home/gisen/pcd/pantory/result/result3.txt"

# Camera Parameters. Adjust them!
camera:
  camera_matrix:
    [348.79196, 0., 328.71776, 0., 349.27022, 234.46734, 0., 0., 1.]
  dist_coeffs: [-0.008912, -0.008214, -0.000225, 0.000351, 0.000000]

# Calibration Parameters.!
calib:
  calib_config_file: "/home/gisen/ros/src/livox_camera_calib/config/config_indoor.yaml"
  use_rough_calib: true # set true if your initial_extrinsic is bad
