# Data path. adjust them!
common:
  image_path: "/home/gisen/pcd/pantory/pic"
  pcd_path: "/home/gisen/pcd/pantory/pid"
  result_path: "/home/gisen/pcd/pantory/result/result2.txt"
  data_num: 3

# common:
#   image_path: "/home/gisen/pcd/pantory/pic"
#   pcd_path: "/home/gisen/pcd/pantory/pid"
#   result_path: "/home/gisen/pcd/pantory/result/result2.txt"
#   data_num: 3

# Camera Parameters. Adjust them!
camera:
  camera_matrix:
    [
      233.3038252725968,
      0,
      367.5536677304368,
      0,
      233.0751416669911,
      367.0886110159834,
      0,
      0,
      1,
    ]
  dist_coeffs:
    [
      -0.02736829209441808,
      0.01676332235440696,
      -0.0138297037587819,
      0.003084867513649774,
      0.0,
    ]

# Calibration Parameters.!
calib:
  calib_config_file: "/home/gisen/ros/src/livox_camera_calib/config/config_indoor.yaml"
  use_rough_calib: true # set true if your initial_extrinsic is bad
